blueprints/spicy_sweet/routes.py
from datetime import datetime, timedelta
from flask import Blueprint, flash, render_template, request, redirect, url_for, session, jsonify
from sqlalchemy import func
from blueprints.spicy_sweet.models import db, almacen, historial, vista_productos, vista_ingredientes, vista_varios

spicy_sweet = Blueprint('spicy_sweet', 
                __name__,
                template_folder='templates',
                static_folder='static',
                static_url_path='/static/spicy_sweet')

users = {'admin': 'admin'}

@spicy_sweet.route('/')
def index():
    if session.get('logged_in'):
        return redirect(url_for('spicy_sweet.home'))
    else:
        return redirect(url_for('spicy_sweet.login'))


@spicy_sweet.route('/login', methods=['GET', 'POST'])
def login(): 
    if request.method == 'GET':
        if session.get('logged_in'):
            return redirect(url_for('spicy_sweet.home'))
        else:
            return render_template('spicy_sweet/login.html')
        
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if username in users and users[username] == password:
            session['logged_in'] = True
            return redirect(url_for('spicy_sweet.home'))
        else:
            error = 'Usuario o contraseña incorrectos'
            return render_template('spicy_sweet/login.html', error=error)


@spicy_sweet.route('/home')
def home():
    if session.get('logged_in'):
        # OBTENER TABLA
        if request.method == 'GET':
            # TOTAL DE VENTAS
            totalVentas = db.session.query(func.round(func.sum(historial.monto), 2)).filter(historial.tipo == 'venta', historial.fecha >= datetime.now() - timedelta(days=30)).scalar()
            totalVentas = totalVentas if totalVentas is not None else 0.0
            # TOTAL DE INVERSIÓN
            totalInversion = db.session.query(func.round(func.sum(historial.monto), 2)).filter(historial.tipo == 'inversion', historial.fecha >= datetime.now() - timedelta(days=30)).scalar()
            totalInversion = totalInversion if totalInversion is not None else 0.0
            # TOTAL DE GANANCIAS
            totalGanancias = round(totalVentas - totalInversion, 2)
            # MÁS VENDIDOS
            masVendidos = db.session.query(
                 almacen.nombre.label('nombre_almacen'),
                    func.sum(historial.cantidad).label('cantidad_vendida'),
                    func.round(func.sum(historial.monto), 2).label('monto_total')
                ).join(
                    historial, historial.id_almacen == almacen.id_almacen
                ).filter(
                    historial.tipo == 'venta',
                    historial.fecha >= datetime.now() - timedelta(days=30)
                ).group_by(almacen.nombre).order_by(func.sum(historial.cantidad).desc()).limit(5).all()

            # ÚLTIMAS VENTAS
            ultimasVentas = db.session.query(
                historial.fecha,
                almacen.nombre.label('nombre_producto'),
                historial.cantidad,
                func.round(historial.monto, 2).label('venta_total')
            ).join(
                almacen, historial.id_almacen == almacen.id_almacen
            ).filter(
                historial.tipo == 'venta',
                historial.fecha <= datetime.now().date()
            ).order_by(historial.fecha.desc()).limit(5).all()

            return render_template('spicy_sweet/home.html',
                                   totalVentas=totalVentas,
                                   totalInversion=totalInversion,
                                   totalGanancias=totalGanancias,
                                   masVendidos=masVendidos,
                                   ultimasVentas=ultimasVentas)
    else:
        return redirect(url_for('spicy_sweet.login'))


@spicy_sweet.route('/productos', methods=['GET', 'POST', 'PUT', 'DELETE'])
def productos():
    if session.get('logged_in'):
        
        if request.method == 'GET':
            # OBTENER TABLA
            registros = vista_productos.query.all()
            stock_bajo = db.session.query(vista_productos).filter(vista_productos.existencias < 3).all()
            return render_template('spicy_sweet/producto.html', registros=registros, stock_bajo=stock_bajo)
        
        if request.method == 'POST':   
            # CREAR REGISTRO
            nuevo_almacen = almacen(
                nombre = request.form.get('nombre'),
                costo = request.form.get('precio'),
                descripcion = request.form.get('descripcion'),
                tipo = 'producto'
            )
            db.session.add(nuevo_almacen)
            db.session.commit()
            return render_template('spicy_sweet/producto.html')
        
        if request.method == 'PUT':
            data = request.form
            tipo_operacion = data.get('tipo_operacion')
            # ACTUALIZAR EXISTENCIAS
            if tipo_operacion == 'actualizar_existencias':
                nombreProducto = request.form.get('nombreProducto')
                entradas = int(request.form.get('entradas') or 0)
                salidas = int(request.form.get('salidas') or 0)
                id_almacen = db.session.query(almacen.id_almacen).filter_by(nombre=nombreProducto).scalar() or None
                # CALCULAR CANTIDAD NUEVA
                cantidad_nueva = db.session.query(almacen.cantidad).filter_by(id_almacen=id_almacen).scalar() + entradas - salidas
                # VERIFICAR SI LA CANTIDAD NUEVA ES MAYOR O IGUAL A 0
                if cantidad_nueva >= 0:
                    # ACTUALIZAR CANTIDAD DE EXISTENCIAS EN ALMACEN (SUMA ENTRADAS Y RESTA SALIDAS)
                    db.session.query(almacen).filter_by(id_almacen=id_almacen).update({'cantidad': cantidad_nueva})
                    db.session.commit()
                    # AGREGAR SALIDAS (VENTAS) A HISTORIAL
                    if salidas:
                        nuevo_historial = historial(
                            id_almacen=id_almacen,
                            fecha=datetime.now(),
                            tipo='venta',
                            cantidad=salidas
                        )
                        db.session.add(nuevo_historial)
                        db.session.commit()
                    return jsonify({'message': 'Registro guardado correctamente'}), 200
                else:
                    return jsonify({'error': 'El número de salidas no puede ser mayor al número de existencias actuales.'}), 400
            
            # EDITAR INFORMACIÓN
            elif tipo_operacion == 'editar_informacion':
                nombreProducto = request.form.get('nombreProducto')
                nuevoNombre = request.form.get('newNombre')
                nuevoPrecio = request.form.get('newPrecio')
                nuevaDescripcion = request.form.get('newDescripcion')
                producto = almacen.query.filter_by(nombre=nombreProducto).first()
                if producto:
                    producto.nombre = nuevoNombre
                    producto.costo = nuevoPrecio
                    producto.descripcion = nuevaDescripcion
                    db.session.commit()
                else:
                    flash("El producto no se encontró en la base de datos.")
            return render_template('spicy_sweet/producto.html')

        # ELIMINAR REGISTRO
        if request.method == 'DELETE':
            nombreProducto = request.form.get('nombreProducto')
            id_almacen = db.session.query(almacen.id_almacen).filter_by(nombre=nombreProducto).scalar()
            db.session.query(almacen).filter_by(id_almacen=id_almacen).delete()
            db.session.commit()
            return render_template('spicy_sweet/producto.html')
    else:
        return redirect(url_for('spicy_sweet.login'))


@spicy_sweet.route('/ingredientes', methods=['GET', 'POST', 'PUT', 'DELETE'])
def ingredientes():
    if session.get('logged_in'):

        if request.method == 'GET':
            # OBTENER TABLA
            registros = vista_ingredientes.query.all()
            stock_bajo = db.session.query(vista_ingredientes).filter(vista_ingredientes.existencias < 3).all()
            return render_template('spicy_sweet/ingrediente.html', registros=registros, stock_bajo=stock_bajo)

        if request.method == 'POST':   
            # CREAR REGISTRO
            nuevo_almacen = almacen(
                nombre = request.form.get('nombre'),
                costo = request.form.get('precio'),
                descripcion = request.form.get('descripcion'),
                tipo = 'ingrediente'
            )
            db.session.add(nuevo_almacen)
            db.session.commit()
            return render_template('spicy_sweet/ingrediente.html')
        
        if request.method == 'PUT':
            data = request.form
            tipo_operacion = data.get('tipo_operacion')
            # ACTUALIZAR EXISTENCIAS
            if tipo_operacion == 'actualizar_existencias':
                nombreProducto = request.form.get('nombreProducto')
                entradas = int(request.form.get('entradas') or 0)
                salidas = int(request.form.get('salidas') or 0)
                id_almacen = db.session.query(almacen.id_almacen).filter_by(nombre=nombreProducto).scalar() or None
                # CALCULAR CANTIDAD NUEVA
                cantidad_nueva = db.session.query(almacen.cantidad).filter_by(id_almacen=id_almacen).scalar() + entradas - salidas
                # VERIFICAR SI LA CANTIDAD NUEVA ES MAYOR O IGUAL A 0
                if cantidad_nueva >= 0:
                    # ACTUALIZAR CANTIDAD DE EXISTENCIAS EN ALMACEN (SUMA ENTRADAS Y RESTA SALIDAS)
                    db.session.query(almacen).filter_by(id_almacen=id_almacen).update({'cantidad': cantidad_nueva})
                    db.session.commit()
                    # AGREGAR ENTRADAS (INVERSIÓN) A HISTORIAL

blueprints/spicy_sweet/templates/spicy_sweet/home.html
{% extends "spicy_sweet/sidebar.html" %}

{% block title %}Spicy Sweet - Home{% endblock %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('spicy_sweet.static', filename='css/home.css') }}">
</head>

<body>

    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h1 class="text-left mb-4">Bienvenido</h1>
                <h4 class="text-left">Resumen de los últimos 30 días</h4>
            </div>
            <div class="col-md-6 text-right">
                <img src="{{ url_for('spicy_sweet.static', filename='img/logo-modified.png') }}"
                    class="custom-img img-fluid logo" alt="Logo de Spicy Sweet">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <div class="card border-0 custom-card">
                    <div class="card-body">
                        <h4 class="card-text"> {{totalGanancias}} MXN </h4>
                        <h5 class="card-title">Ganancias</h5>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="card border-0 custom-card">
                    <div class="card-body">
                        <h4 class="card-text"> {{totalVentas}} MXN </h4>
                        <h5 class="card-title">Ventas</h5>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="card border-0 custom-card ">
                    <div class="card-body">
                        <h4 class="card-text"> {{totalInversion}} MXN</h4>
                        <h5 class="card-title">Inversión</h5>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-5">
            <div class="col-md-6">
                <!-- Primera tabla de productos -->
                <h4 class="mt-2 mb-4">Productos más vendidos</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Cantidad</th>
                            <th>Venta total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for registro in masVendidos %}
                        <tr>
                            <td>{{ registro.nombre_almacen }}</td>
                            <td>{{ registro.cantidad_vendida }}</td>
                            <td>{{ registro.monto_total}} MXN</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        
            <div class="col-md-6">
                <h4 class="mt-2 mb-4">Últimas ventas</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Nombre</th>
                            <th>Cantidad</th>
                            <th>Venta total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for registro in ultimasVentas %}
                        <tr>
                            <td>{{ registro.fecha }}</td>
                            <td>{{ registro.nombre_producto }}</td>
                            <td>{{ registro.cantidad}}</td>
                            <td>{{ registro.venta_total }} MXN</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

{% endblock %}

blueprints/spicy_sweet/templates/spicy_sweet/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('spicy_sweet.static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <p>index</p>
    
   <!-- JS -->
    <script src="{{ url_for('spicy_sweet.static', filename='js/main.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blueprints/spicy_sweet/templates/spicy_sweet/ingrediente.html
{% extends "spicy_sweet/sidebar.html" %}

{% block title %}Spicy Sweet - Ingredientes{% endblock %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('spicy_sweet.static', filename='css/table.css') }}">
</head>

<body>

    <div class="container mt-5">
        <h2 class="mb-5 text-center">Inventario de ingredientes</h2>

        <div class="row justify-content-center mb-5">
            <button id="btnAgregarRegistro" class="btn custom-btn d-flex align-items-center">
                <i class="fa-regular fa-square-plus mr-2"></i>
                Agregar ingrediente
            </button>
        </div>

        <!-- STOCK BAJO -->
        {% if stock_bajo %}
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">¡Atención!</h4>
            <p>Algunos productos tienen un stock bajo, te recomendamos revisarlos.</p>
            <hr>
            <p class="mb-0">Productos con stock bajo:</p>
            <ul>
                {% for producto in stock_bajo %}
                <li>{{ producto.nombre }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        
        <!-- AGREGAR REGISTRO -->
        <div class="modal fade" id="modalAgregarRegistro" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Agregar ingrediente</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="formAgregarRegistro">
                            <!-- Campos del formulario -->
                            <div class="form-group">
                                <label for="nombre">Nombre:</label>
                                <input type="text" class="form-control" id="nombre" name="nombre">
                            </div>
                            <div class="form-group">
                                <label for="precio">Precio de compra:</label>
                                <input type="number" class="form-control" id="precio" name="precio" min="0" oninput="this.value = Math.abs(this.value)">
                            </div>
                            <div class="form-group">
                                <label for="descripcion">Descripción:</label>
                                <textarea class="form-control" id="descripcion" name="descripcion" rows="3"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="button" class="btn btn-primary" onclick="guardarAñadirRegistro()">Guardar
                            Producto</button>
                    </div>
                </div>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Precio de compra</th>
                    <th>Descripción</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for registro in registros %}
                <tr>
                    <td>{{ registro.nombre }}</td>
                    <td>{{ registro.existencias }}</td>
                    <td>{{ registro.costo}} MXN</td>
                    <td>{{ registro.descripcion }}</td>
                    <td>
                        <button class="btnActualizarExistencias btn custom-btn" data-nombre="{{ registro.nombre }}">
                            <i class="fa-solid fa-calculator"></i>
                        </button>

                        <button class="btnEditarInfo btn custom-btn" data-nombre="{{ registro.nombre }}"
                            data-precio="{{ registro.costo }}" data-descripcion="{{ registro.descripcion }}">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </button>

                        <button class="btnEliminarRegistro btn custom-btn" data-nombre="{{ registro.nombre }}">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- ACTUALIZAR EXISTENCIAS -->
    <div class="modal fade" id="modalActualizarExistencias" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Actualizar existencias</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="formActualizarExistencias">
                        <!-- Campos del formulario -->
                        <div class="form-group">
                            <label for="entradas">Entradas:</label>
                            <input type="number" class="form-control" id="entradas" name="entradas" min="0" oninput="this.value = Math.abs(this.value)">
                        </div>
                        <div class="form-group">
                            <label for="salidas">Salidas:</label>
                            <input type="number" class="form-control" id="salidas" name="salidas" min="0" oninput="this.value = Math.abs(this.value)">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="guardarActualizarExistencias()">Guardar
                        Producto</button>
                </div>
            </div>
        </div>
    </div>


    <!-- EDITAR INFO -->
    <div class="modal fade" id="modalEditarInfo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar información</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="formEditarInfo">
                        <div class="form-group">

                            <label for="editarNombre">Nombre:</label>
                            <input type="text" class="form-control" id="editarNombre" name="editarNombre">

                            <label for="editarPrecio">Precio de compra:</label>
                            <input type="number" class="form-control" id="editarPrecio" name="editarPrecio" min="0" oninput="this.value = Math.abs(this.value)">

                            <label for="editarDescripcion">Descripción:</label>
                            <textarea class="form-control" id="editarDescripcion" name="editarDescripcion"
                                rows="3"></textarea>

                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="guardarEditarInfo()">Guardar
                        cambios</button>
                </div>
            </div>
        </div>
    </div>

    <!-- ELIMINAR REGISTRO DE INGREDIENTE/PRODUCTO/VARIOS -->
    <div class="modal fade" id="modalEliminarRegistro" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Deseas eliminar este registro?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="formEliminarRegistro">
                        <div class="form-group">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-danger" onclick="guardarEliminarRegistro()">Eliminar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{{ url_for('spicy_sweet.static', filename='js/ingrediente.js') }}"></script>

</body>

</html>

{% endblock %}

blueprints/spicy_sweet/templates/spicy_sweet/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spicy Sweet - Iniciar sesión</title>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('spicy_sweet.static', filename='img/logo-modified.png') }}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('spicy_sweet.static', filename='css/login.css') }}">
</head>

<body>

    <div class="container col-lg-4 col-md-6 col-sm-8 col-10">

        <div class="d-flex justify-content-center">
            <img src="{{ url_for('spicy_sweet.static', filename='img/logo-modified.png') }}"
                class="custom-img img-fluid" alt="Logo de Spicy Sweet">
        </div>


        <h4 class="text-center fw-bold fs-4">Iniciar sesión</h4>
        <p class="text-center text-secondary mb-5">Ingresa tus credenciales</p>

        <form action="{{ url_for('spicy_sweet.login') }}" method="post">
            <div class="form-floating mb-2">
                <input type="text" class="form-control" id="username" name="username" placeholder="Username">
                <label for="username">Nombre de usuario</label>
            </div>
            <div class="form-floating mb-2">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                <!-- #TODO: Implementar "Ocultar/ver"-->
                <label for="password">Contraseña</label>
            </div>
            <div class="form-check mb-5">
                <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                <!-- #TODO: Implementar lógica de "Recordar contraseña" -->
                <label class="form-check-label" for="rememberPasswordCheck">
                    Recordar contraseña
                </label>
            </div>
            <div class="d-grid">
                <button class="custom-btn" type="submit">Iniciar sesión</button>
            </div>
            
            <!-- #TODO: Modificar esto para que se maneje con AJAX -->
            {% if error %}
            <div class="d-grid mt-3 alert alert-danger" role="alert" id="errorAlert">
                {{ error }}
            </div>
            {% endif %}
            
    </div>
    </form>
    </div>


    <!-- Bootstrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- JS -->
    <script src="{{ url_for('spicy_sweet.static', filename='js/login.js') }}"></script>
</body>

</html>

blueprints/spicy_sweet/templates/spicy_sweet/settings.html
{% extends "spicy_sweet/sidebar.html" %}

{% block title %}Spicy Sweet - Settings{% endblock %}

{% block content %}
<h1>demo settings</h1>
<a href="{{ url_for('spicy_sweet.logout') }}">Logout</a>
{% endblock %}

blueprints/spicy_sweet/templates/spicy_sweet/sidebar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Spicy Sweet - Sidebar{% endblock %}</title>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('spicy_sweet.static', filename='img/logo-modified.png') }}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('spicy_sweet.static', filename='css/sidebar.css') }}">
</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav id="sidebar" class="col-1 bg-light sidebar d-flex flex-column align-items-center">
                <!-- Contenido del sidebar -->
                <ul class="nav flex-column text-center">
                    <li class="nav-item mb-4">
                        <a class="nav-link" href="{{ url_for('spicy_sweet.home') }}">
                            <i class="fas fa-house fa-animate-bounce"></i>
                        </a>
                    </li>
                    <li class="nav-item mb-4">
                        <a class="nav-link" href="{{ url_for('spicy_sweet.productos') }}">
                            <i class="fas fa-boxes-packing fa-animate-bounce"></i>
                        </a>
                    </li>
                    <li class="nav-item mb-4">
                        <a class="nav-link" href="{{ url_for('spicy_sweet.ingredientes') }}">
                            <i class="fas fa-pepper-hot fa-animate-bounce"></i>
                        </a>
                    </li>
                    <li class="nav-item mb-4">
                        <a class="nav-link" href="{{ url_for('spicy_sweet.varios') }}">
                            <i class="fas fa-cubes-stacked fa-animate-bounce"></i>
                        </a>
                    </li>
                </ul>
                <div class="nav-item mb-2 mt-auto text-center">
                    <a class="nav-link" href="{{ url_for('spicy_sweet.logout') }}">
                        <i class="fas fa-right-from-bracket fa-animate-bounce"></i>
                    </a>
                </div>
            </nav>
            
            <!-- Contenido principal -->
            <main id="content" class="col-11">
                {% block content %}{% endblock %}
            </main>
        </div>
    </div>

</body>

</html>